version: '3.18'

services:

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres

  pg_admin:
    image: dpage/pgadmin4
    ports: 
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: hello@example.com
      PGADMIN_DEFAULT_PASSWORD: world

  
  # app:
  #   build: 
  #   image : springboot-example
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres_db
  #   networks:
  #     - local
   


networks:
  local:
    name: local
    driver: bridge
